global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-rest'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8081'] # Assuming running on host

  - job_name: 'spring-soap'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'node-graphql'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:4000']
